version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      com.docker.compose.service: grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    labels:
      com.docker.compose.service: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    labels:
      com.docker.compose.service: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    command:
      - '--web.listen-address=:9100'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs

  crappy-api:
    container_name: "crappy-api"
    labels:
      com.docker.compose.service: crappy-api
    entrypoint:
      - "dotnet"
      - "CrappyApi.dll"
    image: "ghcr.io/fernandoescolar/crappy-api:latest"
    ports:
      - "5000:80/tcp"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./simple-log-app:/usr/src/app

  log-app:
    image: simple-log-app:latest
    container_name: log-app
    ports:
      - "5001:5001"
    volumes:
      - ./simple-log-app:/usr/src/app
      - /usr/src/app/node_modules